version: "3.9"

services:
  go-app:
    container_name: go-app
    build: .
    image: wtfbro/go-app:1.0.0
    environment: 
          DATABASE_URL: "host=go_db user=postgres dbname=postgres password=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: {}